<a href="https://colab.research.google.com/github/Kubojah-Dan/kuboja-codeboosters-2026/blob/main/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
df = pd.read_csv("student_performance.csv")

In [3]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [6]:
print("Shape of the dataset: ", df.shape)
print("Number of Students: ", df.shape[0])
print("Number of Columns: ", df.shape[1])

Shape of the dataset:  (30, 13)
Number of Students:  30
Number of Columns:  13

In [7]:
print("Columns in the dataset")
print(df.columns.tolist())

Columns in the dataset
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [8]:
print("Data Types")
df.dtypes

Data Types

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [9]:
## Statistical Summary
#=========================
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [12]:
## Check for Missing values
#===========================
print("Missing value in each column")
print(df.isnull().sum())

print("Vertical missing values", df.isnull().sum().sum())

Missing value in each column
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64
Vertical missing values 0

In [13]:
## View a specific column
#========================
print("Student Name")
print(df['name'])

Student Name
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [16]:
## View Unique Departments
#=========================

print("\033[1mDepartments in the dataset:\033[0m")
print(df['department'].unique())
print("\n\033[1mNumber of Departments:\033[0m")
print((df['department'].value_counts()))

Departments in the dataset:
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

Number of Departments:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [17]:
## Filter Students by Department
#===============================

cs_students = df[df['department'] == 'Computer Science']
print(f"Number of Computer Science Students: {len(cs_students)}")

print("\nComputer Science students:")
print(cs_students[['name', 'math_score', 'science_score', 'english_score', 'programming_score']])

Number of Computer Science Students: 13

Computer Science students:
              name  math_score  science_score  english_score  \
0     Aarav Sharma          85             78             72
1      Priya Patel          76             82             88
4       Arjun Nair          92             88             81
7      Divya Singh          88             91             84
9       Ananya Das          95             89             90
12      Suresh Rao          83             86             77
14     Ajay Tiwari          71             69             64
17  Swati Kulkarni          90             87             85
19    Nisha Kapoor          79             84             81
21     Tanvi Mehta          93             90             88
24       Amit Bose          86             82             79
26   Gaurav Shukla          84             79             75
29  Akanksha Yadav          91             93             87

    programming_score
0                  91
1                  79
4                  95
7                  93
9                  97
12                 88
14                 76
17                 92
19                 83
21                 96
24                 89
26                 87
29                 94

In [20]:
cs_students_high = df[df['attendance_percentage'] > 90]
print(cs_students_high[['name', 'attendance_percentage']])

              name  attendance_percentage
0     Aarav Sharma                     92
3      Sneha Reddy                     95
7      Divya Singh                     96
9       Ananya Das                     98
13   Kavya Nambiar                     91
15    Ritu Agarwal                     93
17  Swati Kulkarni                     94
21     Tanvi Mehta                     97
24       Amit Bose                     91
29  Akanksha Yadav                     95

In [54]:
## Find the top Performing Students
#=================================

df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']
toppers = df[df['total_score'] / 4 > 90]

print("Top Performing Students:")
print(toppers[['name', 'total_score']])

Top Performing Students:
              name  total_score
9       Ananya Das          371
21     Tanvi Mehta          367
29  Akanksha Yadav          365

In [45]:
## Calculate average score per Department
#========================================
dept_avg = df.groupby('department')['total_score'].mean().round(2)
print(dept_avg)

department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

In [53]:
## Printing Department average in Descending order
#===============================================
print(dept_avg.sort_values(ascending=False))

department
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Civil               235.80
Name: total_score, dtype: float64