<a href="https://colab.research.google.com/github/Kubojah-Dan/kuboja-codeboosters-2026/blob/main/DAY2/Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DATABASE FUNDAMENTALS + SQLITE3 FOR STUDENTS DATABASE**

In [1]:
# Import Libraries
#=========================================

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

print("All libraries imported successfully")
print(f"Pandas version: {pd.__version__}")
print(f"SQLite version: {sqlite3.version}")

All libraries imported successfully
Pandas version: 2.2.2
SQLite version: 2.6.0

In [3]:
# Load the Student Dataset
#==================================

df = pd.read_csv('student_performance.csv')
print(f"Dataset Loaded: {df.shape[0]} students, {df.shape[1]} columns")
print(f"Columns: {df.columns.tolist()}")
df.head(10)

Dataset Loaded: 30 students, 13 columns
Columns: ['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023

In [8]:
# Create SQLite database and load Student Data
#===================================================

conn = sqlite3.connect('college.db')

cursor = conn.cursor()
print('Database Created Successfully')

df.to_sql(
    'students',
    conn,
    if_exists='replace',
    index=False
)
cursor.execute("SELECT COUNT(*) FROM students;")
count = cursor.fetchone()[0]
print(f"Number of rows in the 'students' table: {count}")

Database Created Successfully
Number of rows in the 'students' table: 30

In [11]:
select = cursor.execute("SELECT name, math_score FROM students WHERE math_score > 75")
results = select.fetchall()
df_results = pd.DataFrame(results, columns=['Name', 'Math Score'])
display(df_results)

              Name  Math Score
0     Aarav Sharma          85
1      Priya Patel          76
2       Arjun Nair          92
3      Divya Singh          88
4       Ananya Das          95
5      Vikram Iyer          80
6       Suresh Rao          83
7     Ritu Agarwal          87
8   Swati Kulkarni          90
9     Nisha Kapoor          79
10     Tanvi Mehta          93
11   Preeti Saxena          77
12       Amit Bose          86
13   Gaurav Shukla          84
14  Akanksha Yadav          91

In [15]:
query = """
    SELECT student_id, name, department, math_score, attendance_percentage
    FROM students
    LIMIT 10
"""
cursor.execute(query)

results = cursor.fetchall()

df_result1 = pd.DataFrame(results, columns=['Student ID', 'Name', 'Department', 'Math Score', 'Attendance Percentage'])
display(df_result1)

,Student ID,Name,Department,Math Score,Attendance Percentage
0,1001,Aarav Sharma,Computer Science,85,92
1,1002,Priya Patel,Computer Science,76,87
2,1003,Rohit Verma,Electronics,65,78
3,1004,Sneha Reddy,Mechanical,70,95
4,1005,Arjun Nair,Computer Science,92,90
5,1006,Meera Joshi,Electronics,58,72
6,1007,Kiran Kumar,Civil,73,85
7,1008,Divya Singh,Computer Science,88,96
8,1009,Rahul Mishra,Mechanical,62,68
9,1010,Ananya Das,Computer Science,95,98

In [23]:
query2 = """
    SELECT name, Department, math_score
    FROM students
    ORDER BY math_score DESC
    LIMIT 5
"""
cursor.execute(query2)
results = cursor.fetchall()
df_results2 = pd.DataFrame(results, columns=['Name','Department', 'Math Score'])
print(df_results2)

             Name        Department  Math Score
0      Ananya Das  Computer Science          95
1     Tanvi Mehta  Computer Science          93
2      Arjun Nair  Computer Science          92
3  Akanksha Yadav  Computer Science          91
4  Swati Kulkarni  Computer Science          90

In [28]:
#================================================
# Students From CS Department (WHERE Clause)
#================================================

query3 = """
    SELECT name, math_score, science_score, programming_score, attendance_percentage
    FROM students
    WHERE department = 'Computer Science'
    LIMIT 10
"""
cursor.execute(query3)
results = cursor.fetchall()
df_results2 = pd.DataFrame(results, columns=['Name', 'Math Score', 'Science Score', 'Programming Score', 'Attendance Percentage'])
print(df_results2)

             Name  Math Score  Science Score  Programming Score  \
0    Aarav Sharma          85             78                 91
1     Priya Patel          76             82                 79
2      Arjun Nair          92             88                 95
3     Divya Singh          88             91                 93
4      Ananya Das          95             89                 97
5      Suresh Rao          83             86                 88
6     Ajay Tiwari          71             69                 76
7  Swati Kulkarni          90             87                 92
8    Nisha Kapoor          79             84                 83
9     Tanvi Mehta          93             90                 96

   Attendance Percentage
0                     92
1                     87
2                     90
3                     96
4                     98
5                     88
6                     75
7                     94
8                     89
9                     97

In [30]:
#================================================
# Multiple WHERE Conditions
#================================================

query4 = """
    SELECT name, department, attendance_percentage
    FROM students
    WHERE department <> 'Civil' and attendance_percentage > 90
    ORDER BY attendance_percentage DESC
    LIMIT 10
"""
cursor.execute(query4)
results = cursor.fetchall()
df_results2 = pd.DataFrame(results, columns=['Name', 'Department', 'Attendance Percentage'])
print(df_results2)

             Name        Department  Attendance Percentage
0      Ananya Das  Computer Science                     98
1     Tanvi Mehta  Computer Science                     97
2     Divya Singh  Computer Science                     96
3     Sneha Reddy        Mechanical                     95
4  Akanksha Yadav  Computer Science                     95
5  Swati Kulkarni  Computer Science                     94
6    Ritu Agarwal       Electronics                     93
7    Aarav Sharma  Computer Science                     92
8   Kavya Nambiar        Mechanical                     91
9       Amit Bose  Computer Science                     91

In [40]:
#================================================
# BETWEEN, IN KEYWORDS
#================================================

query5 = """
    SELECT name, department, attendance_percentage
    FROM students
    WHERE name BETWEEN 'A' AND 'F'
    ORDER BY name
"""
cursor.execute(query5)
results = cursor.fetchall()
df_results2 = pd.DataFrame(results, columns=['Name', 'Department', 'Attendance Percentage'])
print(df_results2)

             Name        Department  Attendance Percentage
0    Aarav Sharma  Computer Science                     92
1     Ajay Tiwari  Computer Science                     75
2  Akanksha Yadav  Computer Science                     95
3       Amit Bose  Computer Science                     91
4      Ananya Das  Computer Science                     98
5      Arjun Nair  Computer Science                     90
6  Deepak Chauhan        Mechanical                     77
7     Divya Singh  Computer Science                     96

In [49]:
#=======================================================
# GROUP BY Clause with conditions (Filter by department)
#=======================================================

query6 = """
    SELECT
    department,
    COUNT(*) AS student_count,
    ROUND(AVG(math_score), 2) AS avg_math_score,
    ROUND(AVG(science_score), 2) AS avg_science_score,
    ROUND(AVG(programming_score), 2) AS avg_programming_score,
    ROUND(AVG(attendance_percentage), 2) AS avg_attendance
    FROM students
    GROUP BY department
    ORDER BY avg_math_score DESC
"""
cursor.execute(query6)
results = cursor.fetchall()
df_results2 = pd.DataFrame(results, columns=['Department', 'Student Count', 'Average Math Score', 'Average Science Score', 'Average Programming Score', 'Average Attendace'])
print(df_results2.to_string(index=False))

      Department  Student Count  Average Math Score  Average Science Score  Average Programming Score  Average Attendace
Computer Science             13               85.62                  84.46                      89.23              90.69
      Mechanical              6               71.00                  76.50                      49.33              83.50
     Electronics              6               71.00                  74.17                      61.50              80.33
           Civil              5               63.40                  66.60                      40.60              74.60

In [51]:
#================================================
# Departments with AVG Math > 70 (HAVING)
#================================================

query7 = """
    SELECT
    department,
    ROUND(AVG(math_score), 2) AS avg_math_score,
    COUNT(*) AS student_count
    FROM students
    GROUP BY department
    HAVING avg_math_score > 70
    ORDER BY avg_math_score DESC
"""
cursor.execute(query7)
results = cursor.fetchall()
df_results2 = pd.DataFrame(results, columns=['Department', 'Average Math Score', 'Students'])
print(df_results2)

         Department  Average Math Score  Students
0  Computer Science               85.62        13
1        Mechanical               71.00         6
2       Electronics               71.00         6

In [54]:
#================================================
# Gender-wise Performance Analysis
#================================================

query8 = """
    SELECT
    gender,
    COUNT(*) AS total_students,
    ROUND(AVG(math_score), 2) AS avg_math_score,
    ROUND(AVG(programming_score), 2) AS avg_programming_score,
    ROUND(AVG(attendance_percentage), 2) AS avg_attendance
    FROM students
    GROUP BY gender
"""
cursor.execute(query8)
results = cursor.fetchall()
df_results2 = pd.DataFrame(results, columns=['Gender', 'Total Students', 'Average Math Score', 'Average Programming Score', 'Average Attendance'])
print(df_results2.to_string(index=False))

Gender  Total Students  Average Math Score  Average Programming Score  Average Attendance
Female              15               78.47                       70.2               88.53
  Male              15               73.67                       65.0               80.47